457 replace request module
vvo/selenium-standalone pull request #487
Opened 2020-11-24 08:55 UTC by thomasschuiki

This solves #457 .

I updated all functions using [request](https://github.com/request/request) to use [got](https://github.com/sindresorhus/got) instead. The functions basically had to be rewritten, but the logic remains the same.

All available tests are passing. :)

During testing I had some issues with the remote download locations not responding or taking a long time to repsond. This could probably improved by mocking the responses for development. 

I'm happy about any feedback!

2020-11-24 09:29 UTC, mgrybyk requested changes

2020-11-24 09:29 UTC, mgrybyk commented on lib/install.js
> +          let chunk = (16*1024);
Let's move it to the top of the file

2020-11-24 09:29 UTC, mgrybyk commented on lib/install.js
> +  function getDownloadStream(downloadUrl, cb) {
Can you make the function async inatead?

2020-11-24 09:29 UTC, mgrybyk commented on package.json
> +    "test-install": "mocha -g 'should install'",
Cab you remove this one?

2020-11-24 09:29 UTC, mgrybyk commented on test/default-downloads-test.js
> +  (async () => {
Change the parent function to async

2020-11-24 09:29 UTC, mgrybyk commented on lib/install.js
> +          if(res.statusCode !== 200) {
I guess if status code is not 200 for throws an error so it cannot be ever reached

2020-11-24 09:29 UTC, mgrybyk commented on lib/check-started.js
> +          if(res.statusCode !== 200) {
I guess if status code is not 200 for throws an error so it cannot be ever reached

2020-11-24 09:29 UTC, mgrybyk commented on lib/check-started.js
> +  (async () => {
Can yo define async function outside and then call it here?

2020-11-24 09:29 UTC, mgrybyk commented on test/default-downloads-test.js
> +      if (res.statusCode >= 400) {
I guess this can never happen as far as got throws an error in this case

2020-11-26 13:04 UTC, mgrybyk commented
I'll pick this up, thanks for help!

2020-11-26 13:04 UTC, closed without merging

2020-11-27 07:33 UTC, thomasschuiki commented
Hi,

sorry I couldn't get the comments resolved in time. Glad I could help anyway! :)